### PR TITLE
Create Korean translation

### PR DESCRIPTION
**Pull request by dakeshi**
Related issue #4 
- create
  - en, ko folders in root directory
  - LANGS.md
- copy chapters directory in en, ko
- copy SUMMARY.md in en, ko
- copy BOOKREADME.md in en, ko 
  (It would be failed in GitBook automation process without README file specified in book.json)
- korean translation BOOKREADME.md

### CODE REVIEW

**Comment by dakeshi** [comment]
I test it in gitbook with my forked repo, it is really working. :+1:  I can see multi-languages menu butten .

**Comment by vandadnp** [comment]
That is really amazing. We need to thin about this a bit more. Should I create an Issue as a Discussion and then we can see what the community also thinks?

I am thinking about how/when/how often we translate...

For instance, if you would like to do the translation to Korean, would it be possible for you to keep up with new content all the time? Or is it more feasable to first make an official Release of the book, say v1.0, and then we get translations in place for v1.0?

[Here is the issue up for discussion](https://github.com/crowdsourcebooks/theswiftbook/issues/7)

**Comment by vandadnp** [comment]
@dakeshi 

I will close this PR right now until we have more time to think this through. I hope that's okay.

/v

**Comment by dakeshi** [comment]
I think so. We can discuss it later. No problems. Welcome back, @vandadnp. 👏

**Pull request closed without merging**
