### PR TITLE
Add GitBooks.io usage in README.md

### PR DESCRIPTION
**Pull request by dakeshi**
- Add example images for each step.
- Add download link for editor

### CODE REVIEW

**Comment by vandadnp** [comment]
Fantastic contribution.

I'm merging it. I noticed that the images are hosted statically on GitHub servers, *somewhere*. We need to start thinking where we put images in our repo. An images/ folder?

**Comment by dakeshi** [comment]
Thank you @vandadnp :+1: 
I upload my images with creating issue in my repo and use its url in documents. :laughing:
 
I agree that we need to make images resource folder to keep projects images in one place.
And it is very helpful to create some rules to make image name in contribution guideline.
ex) chapter01_description.png

Which would be better solution to make only one images folder for all documents or  images folder per chapter? In [progit project](https://github.com/progit/progit2), it is located in each chapter.

**Comment by vandadnp** [comment]
From my expeirence at working with O'Reilly, it is usually best to have images agnostic of chapters in which they are used. For instance, imagine an image named like this:

ch01_xcode_create_project.png

And then imagine that we then rename the whole ch01 to something else, then we have to go and rename all those images as well.

But if we have an image named

xcode_create_project.png

then we can use it everywhere without worrying if the prefix is correct or not. Should I add a folder for images to the repo?

**Comment by dakeshi** [comment]
I didn't think of that :+1: 
Yes. Add images folder please. :smile:

**Comment by vandadnp** [comment]
Should all images reside in one folder? I don't think we will have so many images at the end, mainly description and code examples so even if we have a few hundred images, it would be good to have them perhaps in one folder only.

Another reason why 1 folder might be good for all images is that we won't then duplicate the same image in various folders.

I will now create an `images/` folder

**Comment by vandadnp** [comment]
https://github.com/crowdsourcebooks/theswiftbook/commit/2459f5bf4342705f90a29264effea311fc6cb442

**Comment by dakeshi** [comment]
Ah. It is possible to have duplicated naming issues.
Good! :100:

**Pull request merged**
